Interaction
squirrel-project/squirrel_driver pull request #131
Opened 2017-08-07 12:07 UTC by HPovoa

Refactored the Interaction components for Squirrel.

The main change is that all code will be ran from the Raspberry Pi (including serial communication with the interaction board)

2017-08-07 15:07 UTC, ipa-nhg requested changes
@HPovoa good work! :+1: 
Just a comment about the structure, could we merge all the subpackages into one package? at the moment you have a folder (squirrel_interaccion) and inside some packages with generic names (board, launch, screen and speakers). We have two problems: this is not following the structure of the repository and we can not use generic names like launch for a package.

I think that make more sense merge everything together in one package squirrel_interaction, where we have the launch files and the nodes together.
If it is ok for you I can restructure the packages and you can review my suggestion and test it, ok?

2017-08-07 15:07 UTC, NadiaHG commented on squirrel_interaction/board/src/teleop.py
> +from raspberry_screen.srv import *
rasberry_screen package does not exists

2017-08-07 16:54 UTC, HPovoa commented on squirrel_interaction/board/src/teleop.py
> +from raspberry_screen.srv import *
Yes, you can help me restructure the packages. 

I'll get right on the other raspberry_screen problem, must have been a commit issue.

2017-08-08 07:54 UTC, ipa-nhg commented
@HPovoa please review https://github.com/HPovoa/squirrel_driver/pull/1 and merge if it is ok for you

2017-08-10 10:25 UTC, ipa-nhg commented
@HPovoa please let me know when this is tested and working on the robot to merge the Pull Request
Thanks!

2017-08-10 11:33 UTC, HPovoa commented
Hi Nadia,

The code is working on the robot, I tested it yesterday but today I wanted
to do a quick sweep in case i missed something.

There are still changes I want to make, but this is a good time to merge i
think.

I would ask you to review the code where i publish to /joint_states, it is
in board.py, because I am unsure if this is the correct way to do it.

Very best,
Henrique Póvoa

2017-08-10 11:25 GMT+01:00 Nadia Hammoudeh García <notifications@github.com>
:

> @HPovoa <https://github.com/hpovoa> please let me know when this is
> tested and working on the robot to merge the Pull Request
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/squirrel-project/squirrel_driver/pull/131#issuecomment-321513350>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AbjVJ_541db39zS8olHgKYdu373lcdaOks5sWtqdgaJpZM4OvWS0>
> .
>

2017-08-21 08:24 UTC, ipa-nhg approved these changes

2017-08-21 08:24 UTC, merged